### ISSUE TITLE
Structure HTML

### ISSUE THREAD

**Issue by mednajjar** [mednajjar/Project-C2N3#1]
Organisation de la  contenu #HTML pour avoir un structure facile à traiter.

**Comment by mednajjar** [comment]
la structure html a été ajouter je peut faire la modification à l'avancement de travail.

**Comment by youssefbm** [comment]
Essayer de préparer l’environnement de travail avant de commencer à développer, vous devez être capable de tout faire avec le terminal vscode, du git jusqu'à compilation automatique du code scss.

**Comment by youssefbm** [comment]
Jetez un coup d'oeil sur cette vidéo : https://www.youtube.com/watch?v=yva2bj-lVRA

**Comment by mednajjar** [comment]
d'accord merci 👍
