### ISSUE TITLE
Réalisation de la version Mobile

### ISSUE THREAD

**Issue by mednajjar** [mednajjar/Project-C2N3#3]
A travers la méthode "Mobile first", réaliser la version mobile respecter le Mockup qui a déjà défini en design.

**Comment by mednajjar** [comment]
finalisation la version1 mobile (je peut faire des petites modification après )

**Comment by youssefbm** [comment]
Apparemment le BEM est appliqué correctement. Tu peux fermer l'issue quand tu finalise le code. Bon travail.

**Comment by mednajjar** [comment]
D'accord merci
